FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /usr/src/app

COPY . .

RUN dotnet build -c Release
RUN dotnet publish -c Release

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/bin/Release/net8.0/publish .

EXPOSE 5000

CMD ["dotnet", "fibonacci.dll"]