FROM rust:latest as build

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/target/release/fibonacci .

EXPOSE 5000

CMD ["./fibonacci"]