FROM rust:latest as build

WORKDIR /usr/src/app

COPY . .

RUN rustup target add x86_64-unknown-linux-musl

RUN cargo build --release --target=x86_64-unknown-linux-musl

FROM alpine:latest

WORKDIR /usr/src/app

RUN apk update \
    && apk add --no-cache ca-certificates tzdata libgcc

COPY --from=build /usr/src/app/target/x86_64-unknown-linux-musl/release/fibonacci .

EXPOSE 5000

CMD ["./fibonacci"]
